kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio-test

nodes:
- role: control-plane

- role: worker
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          system-reserved: memory=3Gi
